YouGotAGift/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from rest_framework import routers
from testApp.api.viewsets import UserViewSet, ProductViewSet
from rest_framework.authtoken import views


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'products', ProductViewSet)

urlpatterns = [
    url(r'^testApp/', include('testApp.urls', namespace='testApp', app_name='testApp')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', views.obtain_auth_token)
]

testApp/urls.py
__author__ = 'muhammadshaker'

from django.conf.urls import url

from testApp.views import index, product, tag


urlpatterns = [
    url(r'^$', index.index, name='home_page'),

    url(r'^product/?$', product.index, name='product_index'),
    url(r'^product/(?P<product_id>[0-9]+)$', product.view, name='product_view'),
    url(r'^product/create/?$', product.create, name='product_create'),
    url(r'^product/(?P<product_id>[0-9]+)/update$', product.update, name='product_update'),
    url(r'^product/(?P<product_id>[0-9]+)/delete$', product.delete, name='product_delete'),

    url(r'^tag/?$', tag.index),
    url(r'^tag/search/?$', tag.search, name='tag_search'),


]

testApp/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    tags = models.ManyToManyField(Tag)
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

testApp/forms.py
__author__ = 'muhammadshaker'

from django.forms import ModelForm
from testApp.models import Tag, Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'tags']


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

testApp/views/index.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, 'index/index.html')

testApp/views/product.py
from testApp.forms import ProductForm
from testApp.models import Product

__author__ = 'muhammadshaker'


from django.shortcuts import render, redirect
from django.http import HttpResponse
from testApp.services import get_products, create_product


# Create your views here.
def index(request):
    products = get_products()
    return render(request, 'product/index.html', {'products': products})


def view(request, product_id):
    product = Product.objects.get(pk=product_id)
    return render(request, 'product/view.html', {'product': product})


def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        #TODO: validation
        product = create_product(request.POST['name'], request.POST['tags'])
        if product:
            return redirect('testApp:product_view', product_id=product.id)
    else:
        form = ProductForm()
    return render(request, 'product/create.html', {'form': form})


def update(request, product_id):
    return HttpResponse("update product"+product_id)


def delete(request, product_id):
    return HttpResponse("delete product" + product_id)

testApp/views/tag.py
import json
from django.core import serializers
from testApp.models import Tag

__author__ = 'muhammadshaker'
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return HttpResponse("Hello world.")


# Create your views here.
def search(request):
    tags = Tag.objects.filter(name__contains=request.GET['tag_name'])
    tags_list = [tag.name for tag in tags]
    return HttpResponse(json.dumps(tags_list), content_type="application/json")

testApp/templates/index/index.html
<a href="{% url 'testApp:product_index' %}">Go to products page</a>

testApp/templates/product/create.html
{% if form.errors %}
    <p><strong>{{ form.errors }}</strong></p>
{% endif %}

<form action="{% url 'testApp:product_create' %}" method="post">
    {% csrf_token %}
    <div class="input-filed">
        <label for="name">Name</label>
        <input type="text" name="name">
    </div>

    <div class="input-filed">
        <div class="new-product-tags"></div>
        <label for="tags">Tags</label>
        <input id="tag-text" type="text">
        <input type="button" value="Add Tag" onclick="add_tag()">
    </div>

    <input id="product-tags" type="hidden" name="tags">


    <input type="submit" value="Create Product" />
</form>


{#TODO: create header, footer and move scripts#}
<script type="text/javascript" src="/static/js/jquery.js"></script>
<script type="text/javascript" src="/static/js/jquery-ui.js"></script>
<script type="text/javascript" src="/static/js/jquery.blockUI.js"></script>
<script type="text/javascript" src="/static/js/site.js"></script>
<script type="text/javascript">
        $('#tag-text').autocomplete({
        source: function(request, response){
            var tag_name = $('#tag-text').val().replace(" ","-");
            ajaxGet(
                "{% url 'testApp:tag_search' %}?tag_name="+tag_name,
                function () {
                },
                function (data) {
                    response(data);
                }
            );
        }
    });


    function add_tag(){
        var tag_name = $('#tag-text').val().replace(" ","-");

        if(tag_name == ''){
            alert("Tag can't be empty");
            return;
        }

        $('#product-tags').val($('#product-tags').val()+tag_name+";");
        $('.new-product-tags').html($('.new-product-tags').html()+tag_name+', ');
        $('#tag-text').val('');
    }
</script>

testApp/templates/product/index.html
{% if products %}
    List of Products
    <ul>
    {% for product in products %}
        <li><a href="{% url 'testApp:product_view' product.id %}">{{ product.name }}</a></li>
    {% endfor %}
    </ul>
    <a href="{% url 'testApp:product_create' %}">Create New Product</a>
{% else %}
    <p>Create your first product.</p>
    <a href="{% url 'testApp:product_create' %}">Create New Product</a>
{% endif %}

testApp/templates/product/view.html
<label>Product Name: </label> {{ product.name }} <br>
<label>Product Tags: </label>
{% for tag in product.tags.all  %}
    {{ tag.name }}
{% endfor %}